# Site
repository: aivatoglou/aivatoglou.github.io
favicon: images/favicon.ico

# Personal info
name: Giorgos Aivatoglou
title: Data Analyst | Computer Engineer
email: aivagiorgos@gmail.com
github_username:  aivatoglou
linkedin_username: aivatoglou

# Additional icon links
additional_links:
- title: CV
  icon: fa-readme
  url: https://www.dropbox.com/s/gxon2ktujbs612w/CV.pdf?dl=0

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Giorgos Aivatoglou.
  I’m an electrical and computer engineer working on the research industry.
  My expertise includes machine learning, data analysis and backend software engineering.
  Do not hesitate to visit my github repo or take a look at my CV from the buttons above!

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me

#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true
