# Site
repository: aivatoglou/aivatoglou.github.io
favicon: images/favicon.ico

# Personal info
name: Giorgos Aivatoglou
title: Computer Engineer / Data Analyst
email: aivagiorgos@gmail.com
github_username:  aivatoglou
linkedin_username: aivatoglou

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Giorgos Aivatoglou.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me

#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true